In [1]:
from keras.models import Sequential
from keras import layers
from keras import regularizers
from keras import backend as K
from keras.callbacks import ModelCheckpoint
import os
import pandas as pd
import numpy as np
import tensorflow as tf

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from tensorflow import keras
model = keras.models.load_model("/content/drive/MyDrive/CS 539 Final Project/RNN/training_1/cp.ckpt")


In [3]:
model

In [4]:
tw= pd.read_csv("/content/drive/MyDrive/CS 539 Final Project/Tweet data/tweets_cleaned.csv")
tw

target          id                          date      flag  \
0           0.0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1           0.0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2           0.0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3           0.0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4           0.0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
1599995     1.0  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996     1.0  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997     1.0  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998     1.0  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599999     1.0  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

                    user                                               text  
0        _TheSpecialOne_    - Awww, that's a bummer.  You shoulda got Da...  
1          scotthamilton  is upset that he can't update his Facebook by ...  
2               mattycus   I dived many times for the ball. Managed to s...  
3                ElleCTF    my whole body feels itchy and like its on fire   
4                 Karoli   no, it's not behaving at all. i'm mad. why am...  
...                  ...                                                ...  
1599995  AmandaMarie1028  Just woke up. Having no school is the best fee...  
1599996      TheWDBoards  TheWDB.com - Very cool to hear old Walt interv...  
1599997           bpbabe  Are you ready for your MoJo Makeover? Ask me f...  
1599998     tinydiamondz  Happy 38th Birthday to my boo of alll time!!! ...  
1599999   RyanTrevMorris                           happy charitytuesday      

[1600000 rows x 6 columns]

In [5]:
tw = tw.sample(frac=1).reset_index(drop=True)
tw

target          id                          date      flag  \
0           1.0  1559546923  Sun Apr 19 11:25:34 PDT 2009  NO_QUERY   
1           0.0  2221703441  Thu Jun 18 05:51:49 PDT 2009  NO_QUERY   
2           0.0  1990622596  Mon Jun 01 05:20:51 PDT 2009  NO_QUERY   
3           0.0  1964557224  Fri May 29 14:25:37 PDT 2009  NO_QUERY   
4           1.0  1997401062  Mon Jun 01 16:47:06 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
1599995     1.0  2044632353  Fri Jun 05 09:37:18 PDT 2009  NO_QUERY   
1599996     1.0  2176956887  Mon Jun 15 05:08:23 PDT 2009  NO_QUERY   
1599997     1.0  2004489309  Tue Jun 02 08:16:50 PDT 2009  NO_QUERY   
1599998     0.0  2219267602  Thu Jun 18 00:09:33 PDT 2009  NO_QUERY   
1599999     1.0  1979924381  Sun May 31 05:02:40 PDT 2009  NO_QUERY   

                    user                                               text  
0          amandahoffman                              uploading picturesss   
1           bennythemink   also trying to download iphone 3.0 update 4 i...  
2             alanwardle  _Prefab_77 Mint innit! To be honest though i w...  
3               AnhHoang                                              Nope   
4                 ki2594  Napped up, reenergized and I got a cookies and...  
...                  ...                                                ...  
1599995  acupuncture_doc  Happy client...has neuropathy and walked out o...  
1599996    villetikkanen  _a_evans i also e-mailed them about a screenin...  
1599997    hyper_baffoon  i think im addicted to these traffic light ice...  
1599998           pezrat  last ever school photos today  At least they w...  
1599999  g54zw00dcy4u1ls                                      wow nice eh!   

[1600000 rows x 6 columns]

In [6]:
X = tw['text']
y = tw['target']
print(X)
print(y)

0                                      uploading picturesss 
1           also trying to download iphone 3.0 update 4 i...
2          _Prefab_77 Mint innit! To be honest though i w...
3                                                      Nope 
4          Napped up, reenergized and I got a cookies and...
                                 ...                        
1599995    Happy client...has neuropathy and walked out o...
1599996    _a_evans i also e-mailed them about a screenin...
1599997    i think im addicted to these traffic light ice...
1599998    last ever school photos today  At least they w...
1599999                                        wow nice eh! 
Name: text, Length: 1600000, dtype: object
0          1.0
1          0.0
2          0.0
3          0.0
4          1.0
          ... 
1599995    1.0
1599996    1.0
1599997    1.0
1599998    0.0
1599999    1.0
Name: target, Length: 1600000, dtype: float64


In [7]:
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences
from keras import regularizers

max_words = 5000
max_len = 200

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)
tweets = pad_sequences(sequences, maxlen=max_len)
print(tweets)

[[   0    0    0 ...    0    0 2015]
 [   0    0    0 ...  153 1131   11]
 [   0    0    0 ...   11  853   27]
 ...
 [   0    0    0 ... 1673   14  594]
 [   0    0    0 ...  164   28  686]
 [   0    0    0 ...  246  131 1042]]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tweets, y, test_size=0.2)

In [9]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 62s 6ms/step - loss: 0.4513 - accuracy: 0.7937


[0.45129698514938354, 0.7936624884605408]